insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, unit) values
('phones_tech', 'New Phones', 'Smartphone', 'Samsung Galaxy A05', 'Samsung', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'Samsung Galaxy A15', 'Samsung', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'Tecno Camon 20', 'Tecno', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'Tecno Spark 10', 'Tecno', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'Infinix Note 30', 'Infinix', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'Infinix Smart 8', 'Infinix', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'iPhone 13', 'Apple', 'each'),
('phones_tech', 'New Phones', 'Smartphone', 'iPhone 15', 'Apple', 'each'),
('phones_tech', 'Accessories', 'Screen protector', 'Tempered glass screen protector', null, 'each'),
('phones_tech', 'Accessories', 'Phone case', 'Silicone phone case', null, 'each'),
('phones_tech', 'Accessories', 'USB cable', 'USB-C charging cable', null, 'each'),
('phones_tech', 'Accessories', 'Bluetooth earpiece', 'Bluetooth earpiece', null, 'each'),
('phones_tech', 'Accessories', 'Memory card', 'Memory card 32GB', 'SanDisk', 'each'),
('phones_tech', 'Accessories', 'Memory card', 'Memory card 64GB', 'SanDisk', 'each'),
('phones_tech', 'Accessories', 'Memory card', 'Memory card 128GB', 'SanDisk', 'each'),
('phones_tech', 'Laptops & Tablets', 'Laptop', 'HP Laptop (specify model & specs)', 'HP', 'each'),
('phones_tech', 'Laptops & Tablets', 'Laptop', 'Dell Laptop (specify model & specs)', 'Dell', 'each'),
('phones_tech', 'Laptops & Tablets', 'Laptop', 'Lenovo Laptop (specify model & specs)', 'Lenovo', 'each'),
('phones_tech', 'Laptops & Tablets', 'Tablet', 'Samsung Galaxy Tab', 'Samsung', 'each'),
('phones_tech', 'Internet Gear', 'Mifi router', 'MTN 4G MiFi router', 'MTN', 'each'),
('phones_tech', 'Internet Gear', 'Mifi router', 'Glo 4G MiFi router', 'Glo', 'each'),
('phones_tech', 'Internet Gear', 'Router', 'WiFi router (dual band)', null, 'each');