insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, suggested_price, unit) values
('general_marketplace', 'Household Cleaning Tools', 'Duster', 'Duster', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Air freshener', 'Air freshener', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Room spray', 'Room spray', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Scented candle', 'Scented candle', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Mosquito coil', 'Mosquito coil', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Insecticide', 'Insecticide', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Cockroach killer', 'Cockroach killer', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Ant killer', 'Ant killer', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Fly killer', 'Fly killer', NULL, NULL, NULL),
('general_marketplace', 'Home Fragrance & Pest Control', 'Mothballs', 'Mothballs', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Cooking pot', 'Cooking pot', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Frying pan', 'Frying pan', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Saucepan', 'Saucepan', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Plate', 'Plate', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Bowl', 'Bowl', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Cup', 'Cup', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Mug', 'Mug', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Drinking glass', 'Drinking glass', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Cutlery set', 'Cutlery set', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Kitchen knife', 'Kitchen knife', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Chopping board', 'Chopping board', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Colander', 'Colander', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Sieve', 'Sieve', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Grater', 'Grater', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Peeler', 'Peeler', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Can opener', 'Can opener', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Bottle opener', 'Bottle opener', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Food storage container', 'Food storage container', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Water flask', 'Water flask', NULL, NULL, NULL),
('general_marketplace', 'Kitchenware & Food Storage', 'Thermos', 'Thermos', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Exercise book', 'Exercise book', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Notebook', 'Notebook', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Ballpoint pen', 'Ballpoint pen', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Pencil', 'Pencil', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Eraser', 'Eraser', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Sharpener', 'Sharpener', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Ruler', 'Ruler', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Marker', 'Marker', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Crayon', 'Crayon', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Colour pencil', 'Colour pencil', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Glue', 'Glue', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Scissors', 'Scissors', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Envelope', 'Envelope', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'Folder', 'Folder', NULL, NULL, NULL),
('general_marketplace', 'Stationery & School Supplies', 'File', 'File', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'AA batteries', 'AA batteries', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'AAA batteries', 'AAA batteries', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'LED bulb', 'LED bulb', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Torchlight', 'Torchlight', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Rechargeable lamp', 'Rechargeable lamp', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Extension cord', 'Extension cord', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Plug adaptor', 'Plug adaptor', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Electrical tape', 'Electrical tape', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Phone charger', 'Phone charger', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'USB cable', 'USB cable', NULL, NULL, NULL),
('general_marketplace', 'Electrical & Small Electronics', 'Power bank', 'Power bank', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Dog food', 'Dog food', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Cat food', 'Cat food', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Pet treats', 'Pet treats', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Bird feed', 'Bird feed', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Cat litter', 'Cat litter', NULL, NULL, NULL),
('general_marketplace', 'Pet Food & Pet Care', 'Pet shampoo', 'Pet shampoo', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'First-aid kit', 'First-aid kit', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Plasters', 'Plasters', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Bandages', 'Bandages', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Cotton wool', 'Cotton wool', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Antiseptic', 'Antiseptic', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Hand sanitizer', 'Hand sanitizer', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Thermometer', 'Thermometer', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Face masks', 'Face masks', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'General vitamins', 'General vitamins', NULL, NULL, NULL),
('general_marketplace', 'Health, First Aid & Wellness', 'Oral rehydration product', 'Oral rehydration product', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Engine oil', 'Engine oil', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Brake fluid', 'Brake fluid', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Coolant', 'Coolant', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Transmission fluid', 'Transmission fluid', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Car shampoo', 'Car shampoo', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Car polish', 'Car polish', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Dashboard cleaner', 'Dashboard cleaner', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Car air freshener', 'Car air freshener', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Wiper blades', 'Wiper blades', NULL, NULL, NULL),
('general_marketplace', 'Automotive Care', 'Car cleaning cloth', 'Car cleaning cloth', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Hammer', 'Hammer', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Screwdriver', 'Screwdriver', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Pliers', 'Pliers', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Tape measure', 'Tape measure', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Padlock', 'Padlock', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Nails', 'Nails', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Screws', 'Screws', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Bolts', 'Bolts', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Adhesive', 'Adhesive', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Sealant', 'Sealant', NULL, NULL, NULL),
('general_marketplace', 'Hardware & Home Maintenance', 'Plumbing tape', 'Plumbing tape', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'T-shirt', 'T-shirt', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Socks', 'Socks', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Underwear', 'Underwear', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Slippers', 'Slippers', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Sandals', 'Sandals', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Cap', 'Cap', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Raincoat', 'Raincoat', NULL, NULL, NULL),
('general_marketplace', 'Fashion Basics & Accessories', 'Basic children''s wear', 'Basic children''s wear', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Birthday decorations', 'Birthday decorations', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Party cups', 'Party cups', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Party plates', 'Party plates', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Gift bags', 'Gift bags', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Christmas decorations', 'Christmas decorations', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Easter items', 'Easter items', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Back-to-school supplies', 'Back-to-school supplies', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Picnic supplies', 'Picnic supplies', NULL, NULL, NULL),
('general_marketplace', 'Seasonal, Party & Special Occasion', 'Travel accessories', 'Travel accessories', NULL, NULL, NULL);