insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, suggested_price, unit) values
('general_marketplace', 'Fresh Fruits', 'Pear', 'Pear', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Watermelon', 'Watermelon', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Pineapple', 'Pineapple', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Mango', 'Mango', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Pawpaw / papaya', 'Pawpaw / papaya', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Guava', 'Guava', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Avocado', 'Avocado', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Coconut', 'Coconut', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Grapes', 'Grapes', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Yam', 'Yam', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Sweet potato', 'Sweet potato', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Irish potato', 'Irish potato', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Cassava', 'Cassava', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Cocoyam', 'Cocoyam', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Taro', 'Taro', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Ginger', 'Ginger', NULL, NULL, NULL),
('general_marketplace', 'Tubers & Root Crops', 'Fresh garlic', 'Fresh garlic', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Beef', 'Beef', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Goat meat', 'Goat meat', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Lamb / mutton', 'Lamb / mutton', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Pork', 'Pork', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Minced beef', 'Minced beef', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Beef liver', 'Beef liver', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Beef kidney', 'Beef kidney', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Tripe / offal', 'Tripe / offal', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Whole chicken', 'Whole chicken', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Chicken breast', 'Chicken breast', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Chicken thighs', 'Chicken thighs', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Chicken wings', 'Chicken wings', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Chicken drumsticks', 'Chicken drumsticks', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Turkey', 'Turkey', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Duck', 'Duck', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Sausages', 'Sausages', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Hot dogs', 'Hot dogs', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Bacon', 'Bacon', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Ham', 'Ham', NULL, NULL, NULL),
('general_marketplace', 'Meat & Poultry', 'Corned beef', 'Corned beef', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Tilapia', 'Tilapia', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Catfish', 'Catfish', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Croaker', 'Croaker', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Mackerel', 'Mackerel', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Sardines', 'Sardines', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Tuna', 'Tuna', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Salmon', 'Salmon', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Hake', 'Hake', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Cod', 'Cod', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Prawns', 'Prawns', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Shrimp', 'Shrimp', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Crab', 'Crab', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Crayfish', 'Crayfish', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Stockfish', 'Stockfish', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Smoked fish', 'Smoked fish', NULL, NULL, NULL),
('general_marketplace', 'Fish & Seafood', 'Dried fish', 'Dried fish', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Full-cream milk powder', 'Full-cream milk powder', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Skimmed milk powder', 'Skimmed milk powder', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'UHT milk', 'UHT milk', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Evaporated milk', 'Evaporated milk', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Condensed milk', 'Condensed milk', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Fresh milk', 'Fresh milk', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Flavoured milk', 'Flavoured milk', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Yogurt', 'Yogurt', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Drinking yogurt', 'Drinking yogurt', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Greek yogurt', 'Greek yogurt', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Cheese', 'Cheese', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Cheddar cheese', 'Cheddar cheese', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Mozzarella', 'Mozzarella', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Butter', 'Butter', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Cream', 'Cream', NULL, NULL, NULL),
('general_marketplace', 'Dairy, Eggs & Chilled Foods', 'Eggs', 'Eggs', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Malted beverage', 'Malted beverage', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Cocoa beverage', 'Cocoa beverage', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Chocolate drink', 'Chocolate drink', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Black tea', 'Black tea', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Green tea', 'Green tea', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Herbal tea', 'Herbal tea', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Ginger tea', 'Ginger tea', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Instant coffee', 'Instant coffee', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Ground coffee', 'Ground coffee', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Coffee creamer', 'Coffee creamer', NULL, NULL, NULL),
('general_marketplace', 'Malted, Cocoa, Tea & Coffee', 'Cappuccino mix', 'Cappuccino mix', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Bottled water', 'Bottled water', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Sachet water', 'Sachet water', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Sparkling water', 'Sparkling water', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Fruit juice', 'Fruit juice', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Fruit drink', 'Fruit drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Juice concentrate', 'Juice concentrate', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Energy drink', 'Energy drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Sports drink', 'Sports drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Cola soft drink', 'Cola soft drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Orange soft drink', 'Orange soft drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Lemon-lime soft drink', 'Lemon-lime soft drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Tonic water', 'Tonic water', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Ginger drink', 'Ginger drink', NULL, NULL, NULL),
('general_marketplace', 'Water, Juices & Soft Drinks', 'Iced tea', 'Iced tea', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Corn flakes', 'Corn flakes', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Granola', 'Granola', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Muesli', 'Muesli', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Rolled oats', 'Rolled oats', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Bran cereal', 'Bran cereal', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Peanut butter', 'Peanut butter', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Chocolate spread', 'Chocolate spread', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Jam', 'Jam', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Marmalade', 'Marmalade', NULL, NULL, NULL),
('general_marketplace', 'Breakfast Foods & Spreads', 'Pancake mix', 'Pancake mix', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Biscuits', 'Biscuits', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Cookies', 'Cookies', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Crackers', 'Crackers', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Wafers', 'Wafers', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Potato chips', 'Potato chips', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Plantain chips', 'Plantain chips', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Popcorn', 'Popcorn', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Chin chin', 'Chin chin', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Peanut snacks', 'Peanut snacks', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Chocolate', 'Chocolate', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Sweets', 'Sweets', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Chewing gum', 'Chewing gum', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Toffees', 'Toffees', NULL, NULL, NULL),
('general_marketplace', 'Snacks, Biscuits & Confectionery', 'Candy', 'Candy', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'White bread', 'White bread', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Wheat bread', 'Wheat bread', NULL, NULL, NULL);