insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, suggested_price, unit) values
('general_marketplace', 'Bread & Bakery', 'Whole-grain bread', 'Whole-grain bread', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Buns', 'Buns', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Bread rolls', 'Bread rolls', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Croissants', 'Croissants', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Doughnuts', 'Doughnuts', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Meat pie', 'Meat pie', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Sausage roll', 'Sausage roll', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Cake', 'Cake', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Cupcakes', 'Cupcakes', NULL, NULL, NULL),
('general_marketplace', 'Bread & Bakery', 'Muffins', 'Muffins', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned beans', 'Canned beans', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Baked beans', 'Baked beans', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned peas', 'Canned peas', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned sweet corn', 'Canned sweet corn', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned mushrooms', 'Canned mushrooms', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned fruit', 'Canned fruit', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Canned fish', 'Canned fish', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Sardines', 'Sardines', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Tuna', 'Tuna', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Corned beef', 'Corned beef', NULL, NULL, NULL),
('general_marketplace', 'Canned, Jarred & Preserved Foods', 'Pickles', 'Pickles', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen chicken', 'Frozen chicken', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen turkey', 'Frozen turkey', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen beef', 'Frozen beef', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen fish', 'Frozen fish', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen prawns', 'Frozen prawns', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen vegetables', 'Frozen vegetables', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen peas', 'Frozen peas', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen chips', 'Frozen chips', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen pizza', 'Frozen pizza', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen sausages', 'Frozen sausages', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Ice cream', 'Ice cream', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Frozen yogurt', 'Frozen yogurt', NULL, NULL, NULL),
('general_marketplace', 'Frozen Foods & Ice Cream', 'Ice lollies', 'Ice lollies', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Infant formula', 'Infant formula', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby cereal', 'Baby cereal', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby food', 'Baby food', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby snacks', 'Baby snacks', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby juice', 'Baby juice', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby feeding bottle', 'Baby feeding bottle', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Pacifier', 'Pacifier', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby bib', 'Baby bib', NULL, NULL, NULL),
('general_marketplace', 'Baby Food & Infant Care', 'Baby spoon', 'Baby spoon', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby diapers', 'Baby diapers', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby wipes', 'Baby wipes', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby soap', 'Baby soap', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby lotion', 'Baby lotion', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby oil', 'Baby oil', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby shampoo', 'Baby shampoo', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby powder', 'Baby powder', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby bath wash', 'Baby bath wash', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby cream', 'Baby cream', NULL, NULL, NULL),
('general_marketplace', 'Baby Care & Children''s Essentials', 'Baby towels', 'Baby towels', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Bath soap', 'Bath soap', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Body wash', 'Body wash', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Shower gel', 'Shower gel', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Body lotion', 'Body lotion', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Body cream', 'Body cream', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Body oil', 'Body oil', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Deodorant', 'Deodorant', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Antiperspirant', 'Antiperspirant', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Shampoo', 'Shampoo', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Conditioner', 'Conditioner', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Hair cream', 'Hair cream', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Hair oil', 'Hair oil', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Hair gel', 'Hair gel', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Toothpaste', 'Toothpaste', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Toothbrush', 'Toothbrush', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Mouthwash', 'Mouthwash', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Dental floss', 'Dental floss', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Razors', 'Razors', NULL, NULL, NULL),
('general_marketplace', 'Personal Care & Hygiene', 'Shaving cream', 'Shaving cream', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Sanitary pads', 'Sanitary pads', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Tampons', 'Tampons', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Pantyliners', 'Pantyliners', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Feminine wipes', 'Feminine wipes', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Feminine wash', 'Feminine wash', NULL, NULL, NULL),
('general_marketplace', 'Feminine Care', 'Maternity pads', 'Maternity pads', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Laundry detergent powder', 'Laundry detergent powder', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Liquid laundry detergent', 'Liquid laundry detergent', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Laundry soap', 'Laundry soap', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Fabric softener', 'Fabric softener', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Stain remover', 'Stain remover', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Bleach', 'Bleach', NULL, NULL, NULL),
('general_marketplace', 'Laundry Care', 'Laundry starch', 'Laundry starch', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Dishwashing liquid', 'Dishwashing liquid', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Dishwashing soap', 'Dishwashing soap', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Scouring powder', 'Scouring powder', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Dish sponge', 'Dish sponge', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Scrub pad', 'Scrub pad', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Multi-purpose cleaner', 'Multi-purpose cleaner', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Floor cleaner', 'Floor cleaner', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Toilet cleaner', 'Toilet cleaner', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Bathroom cleaner', 'Bathroom cleaner', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Glass cleaner', 'Glass cleaner', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Disinfectant', 'Disinfectant', NULL, NULL, NULL),
('general_marketplace', 'Dishwashing & Surface Cleaning', 'Drain cleaner', 'Drain cleaner', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Toilet tissue', 'Toilet tissue', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Facial tissue', 'Facial tissue', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Paper towels', 'Paper towels', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Kitchen towels', 'Kitchen towels', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Serviettes / napkins', 'Serviettes / napkins', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Aluminium foil', 'Aluminium foil', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Cling film', 'Cling film', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Baking paper', 'Baking paper', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Garbage bags', 'Garbage bags', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Food storage bags', 'Food storage bags', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Disposable plates', 'Disposable plates', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Disposable cups', 'Disposable cups', NULL, NULL, NULL),
('general_marketplace', 'Paper, Tissue & Disposable Consumables', 'Disposable cutlery', 'Disposable cutlery', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Broom', 'Broom', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Mop', 'Mop', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Dustpan', 'Dustpan', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Cleaning brush', 'Cleaning brush', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Toilet brush', 'Toilet brush', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Bucket', 'Bucket', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Basin', 'Basin', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Clothes pegs', 'Clothes pegs', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Laundry basket', 'Laundry basket', NULL, NULL, NULL),
('general_marketplace', 'Household Cleaning Tools', 'Cleaning gloves', 'Cleaning gloves', NULL, NULL, NULL);