create table public.category_keyword_hints (
  id uuid primary key default uuid_generate_v4(),
  keyword text not null,
  hub text not null,
  category text not null
);

insert into public.category_keyword_hints (keyword, hub, category) values
('seasoning', 'general_marketplace', 'Condiments & spices'),
('cube', 'general_marketplace', 'Condiments & spices'),
('spice', 'general_marketplace', 'Condiments & spices'),
('pepper soup mix', 'general_marketplace', 'Condiments & spices'),
('curry', 'general_marketplace', 'Condiments & spices'),
('thyme', 'general_marketplace', 'Condiments & spices'),
('rice', 'general_marketplace', 'Grains & staples'),
('beans', 'general_marketplace', 'Grains & staples'),
('garri', 'general_marketplace', 'Grains & staples'),
('semovita', 'general_marketplace', 'Grains & staples'),
('flour', 'general_marketplace', 'Grains & staples'),
('millet', 'general_marketplace', 'Grains & staples'),
('sorghum', 'general_marketplace', 'Grains & staples'),
('spaghetti', 'general_marketplace', 'Pasta, Noodles & Grains'),
('noodle', 'general_marketplace', 'Pasta, Noodles & Grains'),
('macaroni', 'general_marketplace', 'Pasta, Noodles & Grains'),
('oil', 'general_marketplace', 'Oils & fats'),
('groundnut oil', 'general_marketplace', 'Oils & fats'),
('milk', 'general_marketplace', 'Dairy & beverages'),
('tomato', 'general_marketplace', 'Fresh produce — vegetables'),
('onion', 'general_marketplace', 'Fresh produce — vegetables'),
('pepper', 'general_marketplace', 'Fresh produce — vegetables'),
('okra', 'general_marketplace', 'Fresh produce — vegetables'),
('spinach', 'general_marketplace', 'Fresh produce — vegetables'),
('banana', 'general_marketplace', 'Fresh produce — fruits'),
('orange', 'general_marketplace', 'Fresh produce — fruits'),
('yam', 'general_marketplace', 'Fresh produce — tubers'),
('potato', 'general_marketplace', 'Fresh produce — tubers'),
('cassava', 'general_marketplace', 'Fresh produce — tubers'),
('fish', 'general_marketplace', 'Fresh meat & fish'),
('meat', 'general_marketplace', 'Fresh meat & fish'),
('chicken', 'general_marketplace', 'Fresh meat & fish'),
('detergent', 'general_marketplace', 'Household & cleaning'),
('soap', 'general_marketplace', 'Household & cleaning'),
('bleach', 'general_marketplace', 'Household & cleaning'),
('diaper', 'general_marketplace', 'Baby — diapers & potty'),
('formula', 'general_marketplace', 'Baby — food & feeding formula'),
('shock absorber', 'general_marketplace', 'Automobile & spare parts'),
('headlight', 'general_marketplace', 'Automobile & spare parts'),
('brake', 'general_marketplace', 'Automobile & spare parts'),
('tyre', 'general_marketplace', 'Automobile & spare parts'),
('battery', 'general_marketplace', 'Automobile & spare parts'),
('phone', 'general_marketplace', 'Phones & accessories'),
('charger', 'general_marketplace', 'Phones & accessories'),
('laptop', 'general_marketplace', 'Computers, tablets & peripherals'),
('cement', 'general_marketplace', 'Building materials'),
('paint', 'general_marketplace', 'Building materials');

alter table public.category_keyword_hints enable row level security;
create policy "Anyone can view real keyword hints" on public.category_keyword_hints for select using (true);