insert into public.neighborhood_areas (name, lga_id)
select v.area_name, l.id
from (values
('Birnin Gwari', 'Magajin Gari I'),('Birnin Gwari', 'Magajin Gari II'),('Birnin Gwari', 'Magajin Gari III'),('Birnin Gwari', 'Awwal'),('Birnin Gwari', 'Gayam'),('Birnin Gwari', 'Kuyelo'),('Birnin Gwari', 'Kazage'),('Birnin Gwari', 'Kakangi'),('Birnin Gwari', 'Tabanni'),('Birnin Gwari', 'Dogon Dawa'),('Birnin Gwari', 'Kutemesi'),('Birnin Gwari', 'Randagi'),
('Chikun', 'Chikun'),('Chikun', 'Gwagwada'),('Chikun', 'Kakau'),('Chikun', 'Kujama'),('Chikun', 'Kunai'),('Chikun', 'Kuriga'),('Chikun', 'Narayi'),('Chikun', 'Nasarawa'),('Chikun', 'Rido'),('Chikun', 'Sabon Tasha'),('Chikun', 'Ung. Yelwa'),('Chikun', 'S/Ggarin Arewa Tirkaniya'),
('Giwa', 'Giwa'),('Giwa', 'Kakangi'),('Giwa', 'Gangara'),('Giwa', 'Shika'),('Giwa', 'Danmahawayi'),('Giwa', 'Yakawada'),('Giwa', 'Idasu'),('Giwa', 'Kidandan'),('Giwa', 'Galadimawa'),('Giwa', 'Kadage'),('Giwa', 'Pan Hauya'),
('Igabi', 'Turunku'),('Igabi', 'Zangon Aya'),('Igabi', 'Gwaraji'),('Igabi', 'Birnin Yero'),('Igabi', 'Igabi'),('Igabi', 'Rigachikun'),('Igabi', 'Afaka'),('Igabi', 'Sabon Birnin Daji'),('Igabi', 'Kerawa'),('Igabi', 'Kwarau'),('Igabi', 'Gadan Gayan'),('Igabi', 'Rigasa'),
('Ikara', 'Ikara'),('Ikara', 'Janfala'),('Ikara', 'K/Kogi'),('Ikara', 'Saulawa'),('Ikara', 'Pala'),('Ikara', 'Saya-Saya'),('Ikara', 'Auchan'),('Ikara', 'Rumi'),('Ikara', 'Paki'),('Ikara', 'Kuya'),
('Jaba', 'Nduyah'),('Jaba', 'Sambam'),('Jaba', 'Fada'),('Jaba', 'Sabchem'),('Jaba', 'Sabzuro'),('Jaba', 'Dura/Bitaro'),('Jaba', 'Daddu'),('Jaba', 'Chori'),('Jaba', 'Nok'),('Jaba', 'Fai'),
('Jema''a', 'Kafanchan A'),('Jema''a', 'Kafanchan B'),('Jema''a', 'Maigizo'),('Jema''a', 'Kaninkon'),('Jema''a', 'Jagindi'),('Jema''a', 'Godogodo'),('Jema''a', 'Gidan Waya'),('Jema''a', 'Atuku'),('Jema''a', 'Asso'),('Jema''a', 'Bedde'),('Jema''a', 'Kagoma'),('Jema''a', 'Takau'),
('Kachia', 'Agunu'),('Kachia', 'Awon'),('Kachia', 'Doka'),('Kachia', 'Gumel'),('Kachia', 'Gidan Tagwai'),('Kachia', 'Kwaturu'),('Kachia', 'Ankwa'),('Kachia', 'Katari'),('Kachia', 'Bishini'),('Kachia', 'Kachia Urban'),('Kachia', 'Sabon Sarki'),('Kachia', 'Kurmin Musa'),
('Kaduna North', 'Shaba'),('Kaduna North', 'Gaji'),('Kaduna North', 'Unguwan Liman'),('Kaduna North', 'Maiburji'),('Kaduna North', 'Kabala Costain/Doki'),('Kaduna North', 'Gabasawa'),('Kaduna North', 'Unguwan Sarki'),('Kaduna North', 'Badarawa'),('Kaduna North', 'Unguwan Dosa'),('Kaduna North', 'Kawo'),('Kaduna North', 'Hayin Banki'),('Kaduna North', 'Unguwan Shanu'),
('Kaduna South', 'Makera'),('Kaduna South', 'Barnawa'),('Kaduna South', 'Kakuri Gwari'),('Kaduna South', 'Television'),('Kaduna South', 'Kakuri Hausa'),('Kaduna South', 'Tudun Wada North'),('Kaduna South', 'Tudun Wada South'),('Kaduna South', 'Tudun Wada West'),('Kaduna South', 'Tudun Nuwapa'),('Kaduna South', 'Sabon Gari South'),('Kaduna South', 'Sabon Gari North'),('Kaduna South', 'Ung. Sanusi'),('Kaduna South', 'Badiko'),
('Kagarko', 'Aribi'),('Kagarko', 'Iddah'),('Kagarko', 'Jere North'),('Kagarko', 'Jere South'),('Kagarko', 'Kagarko North'),('Kagarko', 'Kagarko South'),('Kagarko', 'Katugal'),('Kagarko', 'Kukui'),('Kagarko', 'Kurmin Jibrin'),('Kagarko', 'Kushe'),
('Kajuru', 'Afogo'),('Kajuru', 'Buda'),('Kajuru', 'Idon'),('Kajuru', 'Kajuru'),('Kajuru', 'Kallah'),('Kajuru', 'Kasuwan Magani'),('Kajuru', 'Kufana'),('Kajuru', 'Maro'),('Kajuru', 'Rimau'),('Kajuru', 'Tantatu'),
('Kaura', 'Kaura Town'),('Kaura', 'Manchok'),('Kaura', 'Kagoro'),('Kaura', 'Zankan'),('Kaura', 'Kukum Daji'),('Kaura', 'Fadan Takad'),('Kaura', 'Kadarko'),('Kaura', 'Bondong'),('Kaura', 'Garaji'),('Kaura', 'Fadan Attakar'),('Kaura', 'Fada Ciki Gari'),('Kaura', 'Biniki'),('Kaura', 'Zumuruk'),
('Kauru', 'Badurum Sama'),('Kauru', 'Bital'),('Kauru', 'Damakasuwa'),('Kauru', 'Dawaki'),('Kauru', 'Geshere'),('Kauru', 'Kamaru'),('Kauru', 'Pari'),('Kauru', 'Kauru East'),('Kauru', 'Kauru West'),('Kauru', 'Kwassam'),('Kauru', 'Makami'),
('Kubau', 'Anchau'),('Kubau', 'Pambegua'),('Kubau', 'Zuntu'),('Kubau', 'Dutsen-wai'),('Kubau', 'Damau'),('Kubau', 'Kargi'),('Kubau', 'Karreh'),('Kubau', 'Mah'),('Kubau', 'Kubau'),('Kubau', 'Haskiya'),('Kubau', 'Zabi'),
('Kudan', 'Kudan'),('Kudan', 'Hunkuyi'),('Kudan', 'Sabon Gari Hunkuyi'),('Kudan', 'Garu'),('Kudan', 'Zabi'),('Kudan', 'Doka'),('Kudan', 'Likoro'),('Kudan', 'Taban Sani'),('Kudan', 'Kauran Wali North'),('Kudan', 'Kauran Wali South'),
('Lere', 'Abadawa'),('Lere', 'Dan Alhaji'),('Lere', 'Garu Mariri'),('Lere', 'Gure Kahugu'),('Lere', 'Kayarda'),('Lere', 'Kudaru'),('Lere', 'Lazuru'),('Lere', 'Lere'),('Lere', 'Raminkura'),('Lere', 'Sabon Birni'),('Lere', 'Saminaka'),
('Makarfi', 'Makarfi'),('Makarfi', 'Tudun Wada'),('Makarfi', 'Gazara'),('Makarfi', 'Danguziri'),('Makarfi', 'Gimi'),('Makarfi', 'Nasarawan Doya'),('Makarfi', 'Mayere'),('Makarfi', 'Gubuchi'),('Makarfi', 'Gwanki'),('Makarfi', 'Dandamisa'),
('Sanga', 'Wasa Station'),('Sanga', 'Arak'),('Sanga', 'Nandu'),('Sanga', 'Gwantu'),('Sanga', 'Ninzam North'),('Sanga', 'Ninzam South'),('Sanga', 'Ninzam West'),('Sanga', 'Ayu'),('Sanga', 'Bokana'),('Sanga', 'Aboro'),('Sanga', 'Fadan Karshi'),
('Sabon Gari', 'Samaru'),('Sabon Gari', 'Basawa'),('Sabon Gari', 'Bomo'),('Sabon Gari', 'Jama''a'),('Sabon Gari', 'Chikaji'),('Sabon Gari', 'Dogarawa'),('Sabon Gari', 'Hanwa'),('Sabon Gari', 'Jushin Waje'),('Sabon Gari', 'Muchia'),('Sabon Gari', 'Unguwan Gabas'),('Sabon Gari', 'Zabi'),
('Soba', 'Soba Town'),('Soba', 'Turawa'),('Soba', 'Richifa'),('Soba', 'Rahama'),('Soba', 'Dan Wata'),('Soba', 'Gimba'),('Soba', 'Kinkiba'),('Soba', 'Garun Gwanki'),('Soba', 'Kwassallo'),('Soba', 'Maigana'),('Soba', 'Gamagira'),('Soba', 'Kaware'),('Soba', 'Matari'),('Soba', 'Awai'),('Soba', 'Yakasai'),('Soba', 'Tudun Saibu'),('Soba', 'Dinya'),
('Zangon Kataf', 'Gora'),('Zangon Kataf', 'Zonzon'),('Zangon Kataf', 'Zaman Dabo'),('Zangon Kataf', 'Unguwar Gaiya'),('Zangon Kataf', 'Zonkwa'),('Zangon Kataf', 'Madakiya'),('Zangon Kataf', 'Unguwar Rimi'),('Zangon Kataf', 'Gidan Jatau'),('Zangon Kataf', 'Kamantan'),('Zangon Kataf', 'Kamuru Ikulu North'),('Zangon Kataf', 'Zango Urban'),
('Zaria', 'Tudun Wada'),('Zaria', 'Dambo'),('Zaria', 'Gyallesu'),('Zaria', 'Kaura'),('Zaria', 'Kufena'),('Zaria', 'Kwarbai A'),('Zaria', 'Kwarbai B'),('Zaria', 'Tukur Tukur'),('Zaria', 'Unguwar Fatika'),('Zaria', 'Unguwar Juma'),('Zaria', 'Limancin-Kona'),('Zaria', 'Wuciciri'),('Zaria', 'Dutsen Abba')
) as v(lga_name, area_name)
join public.local_government_areas l on l.name = v.lga_name
join public.states s on s.id = l.state_id and s.name = 'Kaduna';
