insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, suggested_price, unit) values
('general_marketplace', 'Staple Foods & Grains', 'Parboiled rice', 'Parboiled rice', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Long-grain rice', 'Long-grain rice', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Local rice', 'Local rice', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Basmati rice', 'Basmati rice', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Brown rice', 'Brown rice', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Maize', 'Maize', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Millet', 'Millet', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Sorghum', 'Sorghum', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Oats', 'Oats', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Wheat', 'Wheat', NULL, NULL, NULL),
('general_marketplace', 'Staple Foods & Grains', 'Couscous', 'Couscous', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Brown beans', 'Brown beans', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Honey beans', 'Honey beans', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'White beans', 'White beans', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Soybeans', 'Soybeans', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Chickpeas', 'Chickpeas', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Lentils', 'Lentils', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Green peas', 'Green peas', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Bambara nuts', 'Bambara nuts', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Groundnuts', 'Groundnuts', NULL, NULL, NULL),
('general_marketplace', 'Beans, Legumes & Nuts', 'Cashew nuts', 'Cashew nuts', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Wheat flour', 'Wheat flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Bread flour', 'Bread flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Cake flour', 'Cake flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Semolina', 'Semolina', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Cassava flour', 'Cassava flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Yam flour', 'Yam flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Plantain flour', 'Plantain flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Corn flour', 'Corn flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Rice flour', 'Rice flour', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Baking powder', 'Baking powder', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Baking soda', 'Baking soda', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Dry yeast', 'Dry yeast', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Corn starch', 'Corn starch', NULL, NULL, NULL),
('general_marketplace', 'Flour, Semolina & Baking', 'Custard powder', 'Custard powder', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Spaghetti', 'Spaghetti', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Macaroni', 'Macaroni', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Penne pasta', 'Penne pasta', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Fusilli pasta', 'Fusilli pasta', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Vermicelli', 'Vermicelli', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Instant noodles', 'Instant noodles', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Rice noodles', 'Rice noodles', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Egg noodles', 'Egg noodles', NULL, NULL, NULL),
('general_marketplace', 'Pasta & Noodles', 'Lasagna sheets', 'Lasagna sheets', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Palm oil / red oil', 'Palm oil / red oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Vegetable oil', 'Vegetable oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Groundnut oil', 'Groundnut oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Soybean oil', 'Soybean oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Sunflower oil', 'Sunflower oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Canola oil', 'Canola oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Olive oil', 'Olive oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Coconut oil', 'Coconut oil', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Margarine', 'Margarine', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Butter', 'Butter', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Ghee', 'Ghee', NULL, NULL, NULL),
('general_marketplace', 'Cooking Oils, Fats & Spreads', 'Shortening', 'Shortening', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Granulated white sugar', 'Granulated white sugar', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Brown sugar', 'Brown sugar', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Icing sugar', 'Icing sugar', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Iodized salt', 'Iodized salt', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Sea salt', 'Sea salt', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Rock salt', 'Rock salt', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Honey', 'Honey', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Table sweetener', 'Table sweetener', NULL, NULL, NULL),
('general_marketplace', 'Sugar, Salt & Sweeteners', 'Glucose syrup', 'Glucose syrup', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Curry powder', 'Curry powder', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Thyme', 'Thyme', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Rosemary', 'Rosemary', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Bay leaves', 'Bay leaves', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Cinnamon', 'Cinnamon', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Nutmeg', 'Nutmeg', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Cloves', 'Cloves', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Black pepper', 'Black pepper', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Chilli powder', 'Chilli powder', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Paprika', 'Paprika', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Turmeric', 'Turmeric', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Ginger powder', 'Ginger powder', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Garlic powder', 'Garlic powder', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Stock cubes', 'Stock cubes', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Bouillon powder', 'Bouillon powder', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Ketchup', 'Ketchup', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Mayonnaise', 'Mayonnaise', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Mustard', 'Mustard', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Soy sauce', 'Soy sauce', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Hot sauce', 'Hot sauce', NULL, NULL, NULL),
('general_marketplace', 'Spices, Seasonings & Condiments', 'Vinegar', 'Vinegar', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Fresh tomatoes', 'Fresh tomatoes', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Tomato paste', 'Tomato paste', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Tomato puree', 'Tomato puree', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Canned tomatoes', 'Canned tomatoes', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Tomato sauce', 'Tomato sauce', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Pepper sauce', 'Pepper sauce', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Chilli sauce', 'Chilli sauce', NULL, NULL, NULL),
('general_marketplace', 'Tomatoes, Pepper & Cooking Sauces', 'Pasta sauce', 'Pasta sauce', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Fresh onions', 'Fresh onions', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Spring onions', 'Spring onions', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Fresh pepper', 'Fresh pepper', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Green pepper', 'Green pepper', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Red pepper', 'Red pepper', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Scotch bonnet', 'Scotch bonnet', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Fresh okra', 'Fresh okra', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Spinach', 'Spinach', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Ugu', 'Ugu', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Waterleaf', 'Waterleaf', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Lettuce', 'Lettuce', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Cabbage', 'Cabbage', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Carrot', 'Carrot', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Cucumber', 'Cucumber', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Green beans', 'Green beans', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Garden egg', 'Garden egg', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Eggplant', 'Eggplant', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Broccoli', 'Broccoli', NULL, NULL, NULL),
('general_marketplace', 'Fresh Vegetables', 'Cauliflower', 'Cauliflower', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Banana', 'Banana', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Plantain', 'Plantain', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Orange', 'Orange', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Tangerine', 'Tangerine', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Lemon', 'Lemon', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Lime', 'Lime', NULL, NULL, NULL),
('general_marketplace', 'Fresh Fruits', 'Apple', 'Apple', NULL, NULL, NULL);