insert into public.states (name, code, geopolitical_zone, is_launched) values
('Abia', 'AB', 'South East', false),
('Adamawa', 'AD', 'North East', false),
('Akwa Ibom', 'AK', 'South South', false),
('Anambra', 'AN', 'South East', false),
('Bauchi', 'BA', 'North East', false),
('Bayelsa', 'BY', 'South South', false),
('Benue', 'BE', 'North Central', false),
('Borno', 'BO', 'North East', false),
('Cross River', 'CR', 'South South', false),
('Delta', 'DE', 'South South', false),
('Ebonyi', 'EB', 'South East', false),
('Edo', 'ED', 'South South', false),
('Ekiti', 'EK', 'South West', false),
('Enugu', 'EN', 'South East', false),
('Federal Capital Territory', 'FC', 'North Central', false),
('Gombe', 'GO', 'North East', false),
('Imo', 'IM', 'South East', false),
('Jigawa', 'JI', 'North West', false),
('Kaduna', 'KD', 'North West', true),
('Kano', 'KN', 'North West', false),
('Katsina', 'KT', 'North West', false),
('Kebbi', 'KE', 'North West', false),
('Kogi', 'KO', 'North Central', false),
('Kwara', 'KW', 'North Central', false),
('Lagos', 'LA', 'South West', false),
('Nasarawa', 'NA', 'North Central', false),
('Niger', 'NI', 'North Central', false),
('Ogun', 'OG', 'South West', false),
('Ondo', 'ON', 'South West', false),
('Osun', 'OS', 'South West', false),
('Oyo', 'OY', 'South West', false),
('Plateau', 'PL', 'North Central', false),
('Rivers', 'RI', 'South South', false),
('Sokoto', 'SO', 'North West', false),
('Taraba', 'TA', 'North East', false),
('Yobe', 'YO', 'North East', false),
('Zamfara', 'ZA', 'North West', false);
