insert into public.master_catalog_items (hub, category, base_item, variant_name, unit) values
('automobile', 'Tires & Batteries', 'Tire', 'Tire 175/70R13', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 185/65R14', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 195/65R15', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 205/55R16', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 215/60R16', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 225/45R17', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 235/45R18', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 265/65R17 (SUV)', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 295/80R22.5 (articulated/trailer)', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 315/80R22.5 (articulated/trailer)', 'each'),
('automobile', 'Tires & Batteries', 'Tire', 'Tire 11R22.5 (truck)', 'each');

insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, unit) values
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Synthetic 5W-30, 1L', 'TotalEnergies', '1L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Synthetic 5W-30, 4L', 'TotalEnergies', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Synthetic 5W-30, 20L drum', 'TotalEnergies', '20L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Synthetic 0W-20, 1L', 'Mobil', '1L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Synthetic 0W-20, 4L', 'Mobil', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Fully synthetic 5W-40, 4L', 'Mobil', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Semi-synthetic 15W-40, 4L', 'Oando', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Semi-synthetic 15W-40, 20L drum', 'Oando', '20L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Mineral 20W-50, 1L', 'Conoil', '1L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Mineral 20W-50, 4L', 'Conoil', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Mineral 20W-50, 25L drum (commercial)', 'Conoil', '25L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Fully synthetic 5W-30, 4L', 'Texaco', '4L'),
('automobile', 'Engine Oil & Fluids', 'Engine oil', 'Semi-synthetic 15W-40, 4L', 'Elf', '4L'),
('automobile', 'Engine Oil & Fluids', 'Brake fluid', 'Brake fluid DOT 3', null, '500ml'),
('automobile', 'Engine Oil & Fluids', 'Brake fluid', 'Brake fluid DOT 4', null, '500ml'),
('automobile', 'Engine Oil & Fluids', 'Coolant', 'Engine coolant (ready-mix)', null, '1L'),
('automobile', 'Engine Oil & Fluids', 'Transmission fluid', 'Automatic transmission fluid (ATF)', null, '1L'),
('automobile', 'Engine Oil & Fluids', 'Gear oil', 'Gear oil 80W-90', null, '1L');

insert into public.master_catalog_items (hub, category, base_item, variant_name, brand, unit) values
('automobile', 'Tires & Batteries', 'Car battery', 'Battery 12V 45Ah', 'Exide', 'each'),
('automobile', 'Tires & Batteries', 'Car battery', 'Battery 12V 65Ah', 'Exide', 'each'),
('automobile', 'Tires & Batteries', 'Car battery', 'Battery 12V 75Ah', 'Chloride Exide', 'each'),
('automobile', 'Tires & Batteries', 'Car battery', 'Battery 12V 100Ah (truck/SUV)', 'Chloride Exide', 'each'),
('automobile', 'Tires & Batteries', 'Car battery', 'Battery 12V 65Ah', 'IPS', 'each');

insert into public.master_catalog_items (hub, category, base_item, variant_name, unit) values
('automobile', 'Filters', 'Oil filter', 'Oil filter (universal fit — specify vehicle)', 'each'),
('automobile', 'Filters', 'Air filter', 'Air filter (universal fit — specify vehicle)', 'each'),
('automobile', 'Filters', 'Fuel filter', 'Fuel filter (universal fit — specify vehicle)', 'each'),
('automobile', 'Filters', 'Cabin/AC filter', 'Cabin air filter', 'each'),
('automobile', 'Brakes & Suspension', 'Brake pads', 'Brake pads (front, specify vehicle)', 'set'),
('automobile', 'Brakes & Suspension', 'Brake pads', 'Brake pads (rear, specify vehicle)', 'set'),
('automobile', 'Brakes & Suspension', 'Brake disc', 'Brake disc/rotor', 'each'),
('automobile', 'Brakes & Suspension', 'Shock absorber', 'Shock absorber (front)', 'each'),
('automobile', 'Brakes & Suspension', 'Shock absorber', 'Shock absorber (rear)', 'each'),
('automobile', 'Electrical & Lighting', 'Spark plugs', 'Spark plug (specify vehicle)', 'each'),
('automobile', 'Electrical & Lighting', 'Headlight bulb', 'Headlight bulb H4/H7', 'each'),
('automobile', 'Electrical & Lighting', 'Alternator', 'Alternator (specify vehicle)', 'each'),
('automobile', 'Tools & Equipment', 'Car jack', 'Hydraulic car jack', 'each'),
('automobile', 'Tools & Equipment', 'Jump starter cables', 'Jump starter cables', 'each');

insert into public.master_catalog_items (hub, category, base_item, variant_name, unit) values
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 9k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 14k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 18k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 21k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 22k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold necklace', 'Gold necklace — 24k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold bracelet', 'Gold bracelet — 18k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold bracelet', 'Gold bracelet — 22k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold ring', 'Gold ring — 18k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold ring', 'Gold ring — 22k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold earrings', 'Gold earrings — 18k (pair)', 'per pair (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold chain', 'Gold chain — 18k', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Jewelry', 'Gold pendant', 'Gold pendant — 18k', 'per piece (specify weight)'),
('gold_jewelry', 'Bridal & Traditional', 'Wedding ring set', 'Wedding ring set — 18k', 'set (specify weight)'),
('gold_jewelry', 'Bridal & Traditional', 'Traditional bridal set', 'Traditional bridal set (necklace + earrings)', 'set (specify weight)'),
('gold_jewelry', 'Silver Jewelry', 'Silver necklace', 'Silver necklace — 925 sterling', 'per piece (specify weight)'),
('gold_jewelry', 'Silver Jewelry', 'Silver ring', 'Silver ring — 925 sterling', 'per piece (specify weight)'),
('gold_jewelry', 'Gold Bullion', 'Gold bar', 'Gold bar/ingot (specify weight & purity)', 'per piece (specify weight)'),
('gold_jewelry', 'Gemstone & Diamond', 'Diamond ring', 'Diamond ring (specify carat & gold karat)', 'per piece'),
('gold_jewelry', 'Fashion & Costume Jewelry', 'Fashion necklace', 'Fashion/costume necklace (non-precious)', 'per piece'),
('gold_jewelry', 'Fashion & Costume Jewelry', 'Fashion earrings', 'Fashion/costume earrings (non-precious)', 'per pair');

insert into public.master_catalog_items (hub, category, base_item, variant_name, unit) values
('pharma_medical', 'Equipment', 'Blood pressure monitor', 'Digital BP monitor (arm cuff)', 'each'),
('pharma_medical', 'Equipment', 'Thermometer', 'Digital thermometer', 'each'),
('pharma_medical', 'Equipment', 'Thermometer', 'Infrared/non-contact thermometer', 'each'),
('pharma_medical', 'Equipment', 'Pulse oximeter', 'Fingertip pulse oximeter', 'each'),
('pharma_medical', 'Equipment', 'Glucometer', 'Blood glucose monitor kit', 'each'),
('pharma_medical', 'Equipment', 'Wheelchair', 'Manual wheelchair', 'each'),
('pharma_medical', 'Equipment', 'Crutches', 'Adjustable crutches (pair)', 'pair'),
('pharma_medical', 'Equipment', 'Hospital bed', 'Manual hospital bed', 'each'),
('pharma_medical', 'Equipment', 'Nebulizer', 'Nebulizer machine', 'each'),
('pharma_medical', 'Equipment', 'Oxygen concentrator', 'Oxygen concentrator', 'each'),
('pharma_medical', 'Equipment', 'Weighing scale', 'Digital body weighing scale', 'each'),
('pharma_medical', 'Equipment', 'First aid kit', 'First aid kit (general)', 'each'),
('pharma_medical', 'Personal Care', 'Face masks', 'Surgical face masks', 'box'),
('pharma_medical', 'Personal Care', 'Hand sanitizer', 'Hand sanitizer', '500ml'),
('pharma_medical', 'Personal Care', 'Disposable gloves', 'Disposable examination gloves', 'box');